Traceback (most recent call last):
  File "/Users/christianjclampitt/Documents/wissenschaft/DAGFromCode/scripts/codex_bridge_server.py", line 93, in <module>
    main()
  File "/Users/christianjclampitt/Documents/wissenschaft/DAGFromCode/scripts/codex_bridge_server.py", line 82, in main
    server = HTTPServer((args.host, args.port), Handler)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use
